import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { MarketplaceProvider } from "@heuvera/providers/MarketplaceProvider";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#F3F2ED]" style={{ fontFamily: "Quicksand, sans-serif" }}>
        <MarketplaceProvider>{children}</MarketplaceProvider>
      </body>
    </html>
  );
}
