import type { Metadata } from "next";
import { Quicksand } from "next/font/google"; // Import Quicksand font

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{ fontFamily: 'Quicksand, sans-serif' }}> {/* Apply Quicksand font */}
        {children}
      </body>
    </html>
  );
}
